version: '3.8'

services:
  bot:
    build: .
    container_name: telegram_bot
    restart: always
    env_file:
      - .env
    depends_on:
      - mongodb
      - scylla
    ports:
      - "8000:8000"

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

  scylla:
    image: scylladb/scylla:latest
    container_name: scylladb
    restart: always
    command: --smp 1 --memory 750M --overprovisioned 1
    volumes:
      - scylla_data:/var/lib/scylla
    ports:
      - "9042:9042"

volumes:
  mongodb_data:
  scylla_data: 